//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RVCore.RVServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RVServices.IRVService")]
    public interface IRVService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/StartUp", ReplyAction="http://tempuri.org/IRVService/StartUpResponse")]
        void StartUp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/StartUp", ReplyAction="http://tempuri.org/IRVService/StartUpResponse")]
        System.Threading.Tasks.Task StartUpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/StartUpV", ReplyAction="http://tempuri.org/IRVService/StartUpVResponse")]
        void StartUpV(int version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/StartUpV", ReplyAction="http://tempuri.org/IRVService/StartUpVResponse")]
        System.Threading.Tasks.Task StartUpVAsync(int version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/StartUpV2", ReplyAction="http://tempuri.org/IRVService/StartUpV2Response")]
        void StartUpV2(int vMajor, int vMinor, int vBuild);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/StartUpV2", ReplyAction="http://tempuri.org/IRVService/StartUpV2Response")]
        System.Threading.Tasks.Task StartUpV2Async(int vMajor, int vMinor, int vBuild);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/SendUser", ReplyAction="http://tempuri.org/IRVService/SendUserResponse")]
        string SendUser(string username, string email, int version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/SendUser", ReplyAction="http://tempuri.org/IRVService/SendUserResponse")]
        System.Threading.Tasks.Task<string> SendUserAsync(string username, string email, int version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/CheckPassword", ReplyAction="http://tempuri.org/IRVService/CheckPasswordResponse")]
        string CheckPassword(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/CheckPassword", ReplyAction="http://tempuri.org/IRVService/CheckPasswordResponse")]
        System.Threading.Tasks.Task<string> CheckPasswordAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/CheckPasswordV", ReplyAction="http://tempuri.org/IRVService/CheckPasswordVResponse")]
        string CheckPasswordV(string username, string password, int version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/CheckPasswordV", ReplyAction="http://tempuri.org/IRVService/CheckPasswordVResponse")]
        System.Threading.Tasks.Task<string> CheckPasswordVAsync(string username, string password, int version);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/GetLatestVersion", ReplyAction="http://tempuri.org/IRVService/GetLatestVersionResponse")]
        int GetLatestVersion(int VersionNow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/GetLatestVersion", ReplyAction="http://tempuri.org/IRVService/GetLatestVersionResponse")]
        System.Threading.Tasks.Task<int> GetLatestVersionAsync(int VersionNow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/UpdateCheck", ReplyAction="http://tempuri.org/IRVService/UpdateCheckResponse")]
        bool UpdateCheck(int vMajor, int vMinor, int vBuild);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/UpdateCheck", ReplyAction="http://tempuri.org/IRVService/UpdateCheckResponse")]
        System.Threading.Tasks.Task<bool> UpdateCheckAsync(int vMajor, int vMinor, int vBuild);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/GetUpdateLink", ReplyAction="http://tempuri.org/IRVService/GetUpdateLinkResponse")]
        string GetUpdateLink();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/GetUpdateLink", ReplyAction="http://tempuri.org/IRVService/GetUpdateLinkResponse")]
        System.Threading.Tasks.Task<string> GetUpdateLinkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/SendErrorMessage", ReplyAction="http://tempuri.org/IRVService/SendErrorMessageResponse")]
        void SendErrorMessage(string username, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/SendErrorMessage", ReplyAction="http://tempuri.org/IRVService/SendErrorMessageResponse")]
        System.Threading.Tasks.Task SendErrorMessageAsync(string username, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/SendErrorMessageV", ReplyAction="http://tempuri.org/IRVService/SendErrorMessageVResponse")]
        void SendErrorMessageV(string username, int version, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/SendErrorMessageV", ReplyAction="http://tempuri.org/IRVService/SendErrorMessageVResponse")]
        System.Threading.Tasks.Task SendErrorMessageVAsync(string username, int version, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/SendErrorMessageV2", ReplyAction="http://tempuri.org/IRVService/SendErrorMessageV2Response")]
        void SendErrorMessageV2(string username, int vMajor, int vMinor, int vBuild, string error);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRVService/SendErrorMessageV2", ReplyAction="http://tempuri.org/IRVService/SendErrorMessageV2Response")]
        System.Threading.Tasks.Task SendErrorMessageV2Async(string username, int vMajor, int vMinor, int vBuild, string error);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRVServiceChannel : RVCore.RVServices.IRVService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RVServiceClient : System.ServiceModel.ClientBase<RVCore.RVServices.IRVService>, RVCore.RVServices.IRVService {
        
        public RVServiceClient() {
        }
        
        public RVServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RVServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RVServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RVServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartUp() {
            base.Channel.StartUp();
        }
        
        public System.Threading.Tasks.Task StartUpAsync() {
            return base.Channel.StartUpAsync();
        }
        
        public void StartUpV(int version) {
            base.Channel.StartUpV(version);
        }
        
        public System.Threading.Tasks.Task StartUpVAsync(int version) {
            return base.Channel.StartUpVAsync(version);
        }
        
        public void StartUpV2(int vMajor, int vMinor, int vBuild) {
            base.Channel.StartUpV2(vMajor, vMinor, vBuild);
        }
        
        public System.Threading.Tasks.Task StartUpV2Async(int vMajor, int vMinor, int vBuild) {
            return base.Channel.StartUpV2Async(vMajor, vMinor, vBuild);
        }
        
        public string SendUser(string username, string email, int version) {
            return base.Channel.SendUser(username, email, version);
        }
        
        public System.Threading.Tasks.Task<string> SendUserAsync(string username, string email, int version) {
            return base.Channel.SendUserAsync(username, email, version);
        }
        
        public string CheckPassword(string username, string password) {
            return base.Channel.CheckPassword(username, password);
        }
        
        public System.Threading.Tasks.Task<string> CheckPasswordAsync(string username, string password) {
            return base.Channel.CheckPasswordAsync(username, password);
        }
        
        public string CheckPasswordV(string username, string password, int version) {
            return base.Channel.CheckPasswordV(username, password, version);
        }
        
        public System.Threading.Tasks.Task<string> CheckPasswordVAsync(string username, string password, int version) {
            return base.Channel.CheckPasswordVAsync(username, password, version);
        }
        
        public int GetLatestVersion(int VersionNow) {
            return base.Channel.GetLatestVersion(VersionNow);
        }
        
        public System.Threading.Tasks.Task<int> GetLatestVersionAsync(int VersionNow) {
            return base.Channel.GetLatestVersionAsync(VersionNow);
        }
        
        public bool UpdateCheck(int vMajor, int vMinor, int vBuild) {
            return base.Channel.UpdateCheck(vMajor, vMinor, vBuild);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateCheckAsync(int vMajor, int vMinor, int vBuild) {
            return base.Channel.UpdateCheckAsync(vMajor, vMinor, vBuild);
        }
        
        public string GetUpdateLink() {
            return base.Channel.GetUpdateLink();
        }
        
        public System.Threading.Tasks.Task<string> GetUpdateLinkAsync() {
            return base.Channel.GetUpdateLinkAsync();
        }
        
        public void SendErrorMessage(string username, string error) {
            base.Channel.SendErrorMessage(username, error);
        }
        
        public System.Threading.Tasks.Task SendErrorMessageAsync(string username, string error) {
            return base.Channel.SendErrorMessageAsync(username, error);
        }
        
        public void SendErrorMessageV(string username, int version, string error) {
            base.Channel.SendErrorMessageV(username, version, error);
        }
        
        public System.Threading.Tasks.Task SendErrorMessageVAsync(string username, int version, string error) {
            return base.Channel.SendErrorMessageVAsync(username, version, error);
        }
        
        public void SendErrorMessageV2(string username, int vMajor, int vMinor, int vBuild, string error) {
            base.Channel.SendErrorMessageV2(username, vMajor, vMinor, vBuild, error);
        }
        
        public System.Threading.Tasks.Task SendErrorMessageV2Async(string username, int vMajor, int vMinor, int vBuild, string error) {
            return base.Channel.SendErrorMessageV2Async(username, vMajor, vMinor, vBuild, error);
        }
    }
}
