<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFrameworks>net10.0-windows;net48</TargetFrameworks>
		<UseWindowsForms>true</UseWindowsForms>
		<Configurations>Debug;Release;</Configurations>
		<ForceDesignerDPIUnaware>true</ForceDesignerDPIUnaware>
		<NoWarn>$(NoWarn);WFO1000;CA1416</NoWarn>
		<Platforms>X64;AnyCPU</Platforms>
	</PropertyGroup>
</Project>
